[prompt]
negative_prompt = "(worst quality, low quality, normal quality, lowres, low details, oversaturated, undersaturated, overexposed, underexposed, grayscale, bw:1.4), (watermark, signature, text font, username, error, logo, words, letters, digits, autograph, trademark, name:1.2), (blur, blurry), mutilated, poorly lit, bad shadow, draft, censored, jpeg artifacts, out of focus, duplicate, (airbrushed, cartoon, anime, semi-realistic, cgi, render, blender, digital art, manga, amateur:1.3), (3D ,3D Game, 3D Game Scene, 3D Character:1.1)"
width = 1024
height = 1024
scale = 12
sample_steps = 28
[[prompt.subset]]
prompt = "photo of a detailed female skin, me1anoma on leg, at age 30, high res, high quality"
